#!/bin/bash

# Get repo
git clone https://github.com/gismo/gismo $HOME/gismo

cd $HOME/gismo

# Update submodules 
git submodule update --init --recursive

# Build libraries
mkdir build
cd build
cmake -DGISMO_BUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Debug ..
make gismo
